{{- if .Values.headlessService.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-headless
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.headlessService.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "uptime-kuma.selectorLabels" . | nindent 4 }}
{{- end }}
